services:
  titiler-xarray:
    platform: linux/amd64
    build:
      context: ./geozarr/xarray
    ports:
      - "8080:8080"
    environment:
      # TiTiler Config
      - TITILER_API_DEBUG=TRUE
      - TITILER_API_NAME=TiTiler GeoZarr
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "1"]

  titiler-zarr:
    platform: linux/amd64
    build:
      context: ./geozarr/zarr-python
    ports:
      - "8083:8083"
    command: ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8083", "--workers", "1"]


  async-titiler:
    image: ghcr.io/developmentseed/async-titiler:latest
    ports:
      - "8081:8081"
    environment:
      - ATITILER_API_DEBUG=true
    command: ["uvicorn", "async_titiler.main:app", "--host", "0.0.0.0", "--port", "8081", "--workers", "1"]
