services:
  titiler-eopf:
    platform: linux/amd64
    build:
      context: ./geozarr/.
      dockerfile: dockerfile.geozarr
    ports:
      - "8080:8080"
    environment:
      # TiTiler Config
      - TITILER_API_DEBUG=TRUE
      - TITILER_API_NAME=TiTiler GeoZarr
      # NOT USED, APP will fail to startup without them
      # Ref: https://github.com/EOPF-Explorer/titiler-eopf/blob/641ff4cdc8425cc31fd86206c3515b375e1b9412/titiler/eopf/dependencies.py#L15
      - TITILER_EOPF_STORE_SCHEME=s3
      - TITILER_EOPF_STORE_HOST=esa-zarr-sentinel-explorer-fra
      - TITILER_EOPF_STORE_PATH=tests-output
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "1"]

  async-titiler:
    image: ghcr.io/developmentseed/async-titiler:latest
    ports:
      - "8081:8081"
    environment:
      - ATITILER_API_DEBUG=true
    command: ["uvicorn", "async_titiler.main:app", "--host", "0.0.0.0", "--port", "8081", "--workers", "1"]

  titiler:
    image: ghcr.io/developmentseed/titiler:2.3.0
    ports:
      - "8082:8082"
    environment:
      # GDAL Config
      - GDAL_CACHEMAX=200
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - GDAL_INGESTED_BYTES_AT_OPEN=32768
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      - VSI_CACHE=TRUE
      - VSI_CACHE_SIZE=536870912
      - CPL_VSIL_CURL_CACHE_SIZE=200000000
      # TiTiler Config
      - TITILER_API_DEBUG=TRUE
    command: ["uvicorn", "titiler.application.main:app", "--host", "0.0.0.0", "--port", "8082", "--workers", "1"]
